/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import javax.swing.ImageIcon;
import DBconnect.OracleConnect;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author Medkaffouh
 */
public class ClientUpdate extends javax.swing.JFrame {

    /**
     * Creates new form ClientUpdate
     */
    OracleConnect oc = new OracleConnect();
    Connection con = oc.getConnect();
    PreparedStatement pst;
    Statement st;
    ResultSet rs1;

    public ClientUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 580));
        setMinimumSize(new java.awt.Dimension(350, 580));
        setPreferredSize(new java.awt.Dimension(350, 580));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modifier le client");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Prénom");

        jTextField1.setMaximumSize(new java.awt.Dimension(120, 25));
        jTextField1.setMinimumSize(new java.awt.Dimension(120, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 14));

        jLabel3.setText("Nom");

        jTextField2.setMaximumSize(new java.awt.Dimension(120, 25));
        jTextField2.setMinimumSize(new java.awt.Dimension(120, 25));
        jTextField2.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setToolTipText("");
        jLabel6.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 14));

        jLabel4.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel7.setText("Adresse");

        jTextField3.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField3.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField3.setPreferredSize(new java.awt.Dimension(269, 25));

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel9.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel10.setText("Ville");

        jTextField4.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField4.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField4.setPreferredSize(new java.awt.Dimension(269, 25));

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel11.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel11.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel12.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel12.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel12.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel13.setText("Code postal");

        jTextField5.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField5.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField5.setPreferredSize(new java.awt.Dimension(269, 25));

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel14.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel14.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel15.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel15.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel15.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel16.setText("Numéro de téléphone");

        jTextField6.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField6.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField6.setPreferredSize(new java.awt.Dimension(269, 25));

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel17.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel17.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel18.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel18.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel18.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel19.setText("Adresse e-mail");

        jTextField7.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField7.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField7.setPreferredSize(new java.awt.Dimension(269, 25));

        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel20.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel20.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel21.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel21.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel21.setPreferredSize(new java.awt.Dimension(25, 25));

        jButton1.setText("Modifier");
        jButton1.setMaximumSize(new java.awt.Dimension(269, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(269, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(269, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField8.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField8.setPreferredSize(new java.awt.Dimension(269, 25));

        jLabel22.setText("Client id");
        jLabel22.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel22.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel22.setPreferredSize(new java.awt.Dimension(120, 14));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel10)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel13)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel16)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel19)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            if (jTextField1.getText().isEmpty()) {
                jLabel5.setText("obligatoire");
                jLabel4.setIcon(new ImageIcon("src\\Icons\\error.png"));
            } else if (jTextField2.getText().isEmpty()) {
                jLabel5.setText("");
                jLabel6.setText("obligatoire");
                jLabel4.setIcon(new ImageIcon("src\\Icons\\error.png"));
            } else if (jTextField3.getText().isEmpty()) {
                jLabel5.setText("");
                jLabel6.setText("");
                jLabel4.setIcon(new ImageIcon(""));
                jLabel8.setText("obligatoire");
                jLabel9.setIcon(new ImageIcon("src\\Icons\\error.png"));
            } else if (jTextField4.getText().isEmpty()) {
                jLabel5.setText("");
                jLabel6.setText("");
                jLabel4.setIcon(new ImageIcon(""));
                jLabel8.setText("");
                jLabel9.setIcon(new ImageIcon(""));
                jLabel11.setText("obligatoire");
                jLabel12.setIcon(new ImageIcon("src\\Icons\\error.png"));
            } else if (jTextField5.getText().isEmpty()) {
                jLabel5.setText("");
                jLabel6.setText("");
                jLabel4.setIcon(new ImageIcon(""));
                jLabel8.setText("");
                jLabel9.setIcon(new ImageIcon(""));
                jLabel11.setText("");
                jLabel12.setIcon(new ImageIcon(""));
                jLabel14.setText("obligatoire");
                jLabel15.setIcon(new ImageIcon("src\\Icons\\error.png"));
            } else if (jTextField6.getText().isEmpty()) {
                jLabel5.setText("");
                jLabel6.setText("");
                jLabel4.setIcon(new ImageIcon(""));
                jLabel8.setText("");
                jLabel9.setIcon(new ImageIcon(""));
                jLabel11.setText("");
                jLabel12.setIcon(new ImageIcon(""));
                jLabel14.setText("");
                jLabel15.setIcon(new ImageIcon(""));
                jLabel17.setText("obligatoire");
                jLabel18.setIcon(new ImageIcon("src\\Icons\\error.png"));
            } else if (jTextField7.getText().isEmpty()) {
                jLabel5.setText("");
                jLabel6.setText("");
                jLabel4.setIcon(new ImageIcon(""));
                jLabel8.setText("");
                jLabel9.setIcon(new ImageIcon(""));
                jLabel11.setText("");
                jLabel12.setIcon(new ImageIcon(""));
                jLabel14.setText("");
                jLabel15.setIcon(new ImageIcon(""));
                jLabel17.setText("");
                jLabel18.setIcon(new ImageIcon(""));
                jLabel20.setText("obligatoire");
                jLabel21.setIcon(new ImageIcon("src\\Icons\\error.png"));
            } else {
                jLabel5.setText("");
                jLabel6.setText("");
                jLabel4.setIcon(new ImageIcon(""));
                jLabel8.setText("");
                jLabel9.setIcon(new ImageIcon(""));
                jLabel11.setText("");
                jLabel12.setIcon(new ImageIcon(""));
                jLabel14.setText("");
                jLabel15.setIcon(new ImageIcon(""));
                jLabel17.setText("");
                jLabel18.setIcon(new ImageIcon(""));
                jLabel20.setText("");
                jLabel21.setIcon(new ImageIcon(""));
                String fname = jTextField1.getText().trim();
                String lname = jTextField2.getText().trim();
                String adress = jTextField3.getText().trim();
                String city = jTextField4.getText().trim();
                String zip = jTextField5.getText().trim();
                String phone = jTextField6.getText().trim();
                String mail = jTextField7.getText().trim();
                String cus_id = jTextField8.getText().trim();
                String qrr = "select * from customers where email=lower(?) and customer_id=?";
                pst = con.prepareStatement(qrr);
                pst.setString(1, mail);
                pst.setString(2, cus_id);
                rs1 = pst.executeQuery();
                if (rs1.next()) {
                    String sql = "update customers set first_name=initcap('" + fname + "'),last_name=initcap('" + lname + "'),adress='" + adress + "',"
                            + "city=initcap('" + city + "'),zip=" + zip + ",phone_number='" + phone + "',email=initcap('" + mail + "') where customer_id=" + cus_id + "";
                    st = con.createStatement();

                    int res = st.executeUpdate(sql);
                    if (res == 0) {
                        JOptionPane.showMessageDialog(null, "Client non modifier");
                    } else {
                        JOptionPane.showMessageDialog(null, "Client modifier avec succès");
                    }
                } else {
                    String qrr2 = "select * from customers where email=lower(?)";
                pst = con.prepareStatement(qrr2);
                pst.setString(1, mail);
                rs1 = pst.executeQuery();
                if (rs1.next()){
                    jLabel20.setText("l'email existe déjà");
                    jLabel21.setIcon(new ImageIcon("src\\Icons\\error.png"));
                }else{
                    jLabel20.setText("");
                    jLabel21.setIcon(new ImageIcon(""));
                    String sql = "update customers set first_name=initcap('" + fname + "'),last_name=initcap('" + lname + "'),adress='" + adress + "',"
                            + "city=initcap('" + city + "'),zip=" + zip + ",phone_number='" + phone + "',email=lower('" + mail + "') where customer_id=" + cus_id + "";
                    st = con.createStatement();

                    int res = st.executeUpdate(sql);
                    if (res == 0) {
                        JOptionPane.showMessageDialog(null, "Client non modifier");
                    } else {
                        JOptionPane.showMessageDialog(null, "Client modifier avec succès");
                    }
                }
                }

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
