/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import DBconnect.OracleConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author Medkaffouh
 */
public class UserUpdate extends javax.swing.JFrame {

    /**
     * Creates new form UserUpdate
     */
    OracleConnect oc = new OracleConnect();
    Connection con = oc.getConnect();
    PreparedStatement pst1, pst2,pst3;
    Statement st;
    ResultSet rs1, rs2,rs3;

    public UserUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 636));
        setMinimumSize(new java.awt.Dimension(350, 636));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modifier l'utilisateur");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Prénom");

        jTextField1.setMaximumSize(new java.awt.Dimension(120, 25));
        jTextField1.setMinimumSize(new java.awt.Dimension(120, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 14));

        jTextField2.setMaximumSize(new java.awt.Dimension(120, 25));
        jTextField2.setMinimumSize(new java.awt.Dimension(120, 25));
        jTextField2.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel3.setText("Nom");

        jLabel4.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setToolTipText("");
        jLabel6.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 14));

        jTextField3.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField3.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField3.setPreferredSize(new java.awt.Dimension(269, 25));

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel9.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel7.setText("Adresse e-mail");

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel11.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel11.setPreferredSize(new java.awt.Dimension(120, 14));

        jLabel12.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel12.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel12.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel10.setText("Mot de passe");

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setMaximumSize(new java.awt.Dimension(120, 14));
        jLabel14.setMinimumSize(new java.awt.Dimension(120, 14));
        jLabel14.setPreferredSize(new java.awt.Dimension(120, 14));

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel16.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel16.setPreferredSize(new java.awt.Dimension(200, 14));

        jTextField4.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField4.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField4.setPreferredSize(new java.awt.Dimension(269, 25));

        jPasswordField1.setMaximumSize(new java.awt.Dimension(120, 25));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(120, 25));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabel15.setText("Quelle est votre pays d'origine?");

        jLabel17.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel17.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel17.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel13.setText("Confirmer");

        jPasswordField2.setMaximumSize(new java.awt.Dimension(120, 25));
        jPasswordField2.setMinimumSize(new java.awt.Dimension(120, 25));
        jPasswordField2.setPreferredSize(new java.awt.Dimension(120, 25));

        jDateChooser1.setDateFormatString("dd-MMM-yyyy");
        jDateChooser1.setMaximumSize(new java.awt.Dimension(269, 25));
        jDateChooser1.setMinimumSize(new java.awt.Dimension(269, 25));
        jDateChooser1.setPreferredSize(new java.awt.Dimension(269, 25));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Réception" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(269, 25));
        jComboBox1.setMinimumSize(new java.awt.Dimension(269, 25));
        jComboBox1.setPreferredSize(new java.awt.Dimension(269, 25));

        jLabel27.setText("Manageur id");

        jLabel24.setText("Numéro de téléphone");

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel19.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel19.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel25.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel25.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel21.setText("Date de Naissance");

        jTextField6.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField6.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField6.setPreferredSize(new java.awt.Dimension(269, 25));

        jLabel20.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel20.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel20.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel29.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel29.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel29.setPreferredSize(new java.awt.Dimension(25, 25));

        jTextField7.setMaximumSize(new java.awt.Dimension(269, 25));
        jTextField7.setMinimumSize(new java.awt.Dimension(269, 25));
        jTextField7.setPreferredSize(new java.awt.Dimension(269, 25));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });

        jLabel26.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel26.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel26.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel23.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel23.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel23.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel22.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel22.setPreferredSize(new java.awt.Dimension(200, 14));

        jLabel18.setText("Utilisateur est");

        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setMaximumSize(new java.awt.Dimension(200, 14));
        jLabel28.setMinimumSize(new java.awt.Dimension(200, 14));
        jLabel28.setPreferredSize(new java.awt.Dimension(200, 14));

        jButton1.setText("Modifier");
        jButton1.setMaximumSize(new java.awt.Dimension(269, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(269, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(269, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setMaximumSize(new java.awt.Dimension(60, 25));
        jTextField5.setMinimumSize(new java.awt.Dimension(60, 25));
        jTextField5.setPreferredSize(new java.awt.Dimension(60, 25));

        jLabel30.setText("Numéro de Utilisateur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPasswordField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel30)
                .addGap(1, 1, 1)
                .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel15)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jTextField1.getText().isEmpty()) {
            jLabel5.setText("obligatoire");
            jLabel4.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else if (jTextField2.getText().isEmpty()) {
            jLabel5.setText("");
            jLabel6.setText("obligatoire");
            jLabel4.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else if (jTextField3.getText().isEmpty()) {
            jLabel5.setText("");
            jLabel6.setText("");
            jLabel4.setIcon(new ImageIcon(""));
            jLabel8.setText("obligatoire");
            jLabel9.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else if (jPasswordField1.getText().isEmpty()) {
            jLabel5.setText("");
            jLabel6.setText("");
            jLabel4.setIcon(new ImageIcon(""));
            jLabel8.setText("");
            jLabel9.setIcon(new ImageIcon(""));
            jLabel11.setText("obligatoire");
            jLabel12.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else if (jPasswordField2.getText().isEmpty()) {
            jLabel5.setText("");
            jLabel6.setText("");
            jLabel4.setIcon(new ImageIcon(""));
            jLabel8.setText("");
            jLabel9.setIcon(new ImageIcon(""));
            jLabel11.setText("");
            jLabel14.setText("obligatoire");
            jLabel12.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else if (!jPasswordField1.getText().trim().equals(jPasswordField2.getText().trim())) {
            jLabel5.setText("");
            jLabel6.setText("");
            jLabel4.setIcon(new ImageIcon(""));
            jLabel8.setText("");
            jLabel9.setIcon(new ImageIcon(""));
            jLabel11.setText("");
            jLabel14.setText("Confirmation incorrect");
            jLabel12.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else if (jTextField4.getText().isEmpty()) {
            jLabel5.setText("");
            jLabel6.setText("");
            jLabel4.setIcon(new ImageIcon(""));
            jLabel8.setText("");
            jLabel9.setIcon(new ImageIcon(""));
            jLabel11.setText("");
            jLabel14.setText("");
            jLabel12.setIcon(new ImageIcon(""));
            jLabel16.setText("obligatoire");
            jLabel17.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else if (jDateChooser1.getDate() == null) {
            jLabel5.setText("");
            jLabel6.setText("");
            jLabel4.setIcon(new ImageIcon(""));
            jLabel8.setText("");
            jLabel9.setIcon(new ImageIcon(""));
            jLabel11.setText("");
            jLabel14.setText("");
            jLabel12.setIcon(new ImageIcon(""));
            jLabel16.setText("");
            jLabel17.setIcon(new ImageIcon(""));
            jLabel22.setText("obligatoire");
            jLabel23.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else if (jTextField6.getText().isEmpty()) {
            jLabel5.setText("");
            jLabel6.setText("");
            jLabel4.setIcon(new ImageIcon(""));
            jLabel8.setText("");
            jLabel9.setIcon(new ImageIcon(""));
            jLabel11.setText("");
            jLabel14.setText("");
            jLabel12.setIcon(new ImageIcon(""));
            jLabel16.setText("");
            jLabel17.setIcon(new ImageIcon(""));
            jLabel22.setText("");
            jLabel23.setIcon(new ImageIcon(""));
            jLabel25.setText("obligatoire");
            jLabel26.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else {
            jLabel5.setText("");
            jLabel6.setText("");
            jLabel4.setIcon(new ImageIcon(""));
            jLabel8.setText("");
            jLabel9.setIcon(new ImageIcon(""));
            jLabel11.setText("");
            jLabel14.setText("");
            jLabel12.setIcon(new ImageIcon(""));
            jLabel16.setText("");
            jLabel17.setIcon(new ImageIcon(""));
            jLabel22.setText("");
            jLabel23.setIcon(new ImageIcon(""));
            jLabel25.setText("");
            jLabel26.setIcon(new ImageIcon(""));
            try {
                String fname = jTextField1.getText().trim();
                String lname = jTextField2.getText().trim();
                String mail = jTextField3.getText().trim();
                String pass1 = jPasswordField1.getText().trim();
                String pass2 = jPasswordField2.getText().trim();
                String qcheck = jTextField4.getText().trim();
                String isadmin = jComboBox1.getSelectedItem().toString();
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
                String dob = sdf.format(jDateChooser1.getDate());
                String phone = jTextField6.getText().trim();
                String manager = jTextField7.getText().trim();
                String userid = jTextField5.getText().trim();
                String admin;
                if (isadmin.equals("Admin")) {
                    admin = "1";
                } else {
                    admin = "0";
                }
                String qrr = "select * from users where email=lower(?) and user_id=?";
                pst2 = con.prepareStatement(qrr);
                pst2.setString(1, mail);
                pst2.setString(2, userid);
                rs2 = pst2.executeQuery();
                if (rs2.next()) {
                    if (jTextField7.getText().isEmpty()) {

                        String qr2 = "update users set first_name=initcap('" + fname + "'),last_name=initcap('" + lname + "'),phone_number="
                                + "'" + phone + "',email=lower('" + mail + "'),dateofbirth='" + dob + "',isadmin=" + admin + ","
                                + "password='" + pass2 + "',qcheck=initcap('" + qcheck + "')"
                                + ",admin_id=null where user_id=" + userid + "";

                        st = con.createStatement();
                        int res = st.executeUpdate(qr2);
                        if (res == 0) {
                            JOptionPane.showMessageDialog(null, "Utilisateur non modifier");
                        } else {
                            JOptionPane.showMessageDialog(null, "Utilisateur modifier avec succès");
                        }
                    } else {
                        String qr = "select * from users where user_id=?";
                        pst1 = con.prepareStatement(qr);
                        pst1.setString(1, manager);
                        rs1 = pst1.executeQuery();
                        if (rs1.next()) {
                            jLabel28.setText("");
                            jLabel29.setIcon(new ImageIcon(""));
                            String qr2 = "update users set first_name=initcap('" + fname + "'),last_name=initcap('" + lname + "'),phone_number="
                                    + "'" + phone + "',email=lower('" + mail + "'),dateofbirth='" + dob + "',isadmin=" + admin + ","
                                    + "password='" + pass2 + "',qcheck=initcap('" + qcheck + "'),"
                                    + "admin_id=" + manager + " where user_id=" + userid + "";
                            st = con.createStatement();

                            int res = st.executeUpdate(qr2);
                            if (res == 0) {
                                JOptionPane.showMessageDialog(null, "Utilisateur non modifier");
                            } else {
                                JOptionPane.showMessageDialog(null, "Utilisateur modifier avec succès");
                            }
                        } else {
                            jLabel28.setText("Introuvable");
                            jLabel29.setIcon(new ImageIcon("src\\Icons\\error.png"));
                            JOptionPane.showMessageDialog(null, "Définir l'id du manageur ou laissez-le vide");
                        }
                    }
                } else {
                    
                    String qrrr = "select * from users where email=lower(?)";
                pst3 = con.prepareStatement(qrrr);
                pst3.setString(1, mail);
                rs3 = pst3.executeQuery();
                if (rs3.next()){
                    jLabel8.setText("l'email existe déjà");
                    jLabel9.setIcon(new ImageIcon("src\\Icons\\error.png"));
                }else{
                    jLabel8.setText("");
                    jLabel9.setIcon(new ImageIcon(""));
                    if (jTextField7.getText().isEmpty()) {

                        String qr2 = "update users set first_name=initcap('" + fname + "'),last_name=initcap('" + lname + "'),phone_number="
                                + "'" + phone + "',email=lower('" + mail + "'),dateofbirth='" + dob + "',isadmin=" + admin + ","
                                + "password='" + pass2 + "',qcheck=initcap('" + qcheck + "')"
                                + ",admin_id=null where user_id=" + userid + "";

                        st = con.createStatement();
                        int res = st.executeUpdate(qr2);
                        if (res == 0) {
                            JOptionPane.showMessageDialog(null, "Utilisateur non modifier");
                        } else {
                            JOptionPane.showMessageDialog(null, "Utilisateur modifier avec succès");
                        }
                    } else {
                        String qr = "select * from users where user_id=?";
                        pst1 = con.prepareStatement(qr);
                        pst1.setString(1, manager);
                        rs1 = pst1.executeQuery();
                        if (rs1.next()) {
                            jLabel28.setText("");
                            jLabel29.setIcon(new ImageIcon(""));
                            String qr2 = "update users set first_name=initcap('" + fname + "'),last_name=initcap('" + lname + "'),phone_number="
                                    + "'" + phone + "',email=lower('" + mail + "'),dateofbirth='" + dob + "',isadmin=" + admin + ","
                                    + "password='" + pass2 + "',qcheck=initcap('" + qcheck + "'),"
                                    + "admin_id=" + manager + " where user_id=" + userid + "";
                            st = con.createStatement();

                            int res = st.executeUpdate(qr2);
                            if (res == 0) {
                                JOptionPane.showMessageDialog(null, "Utilisateur non modifier");
                            } else {
                                JOptionPane.showMessageDialog(null, "Utilisateur modifier avec succès");
                            }
                        } else {
                            jLabel28.setText("Introuvable");
                            jLabel29.setIcon(new ImageIcon("src\\Icons\\error.png"));
                            JOptionPane.showMessageDialog(null, "Définir l'id du manageur ou laissez-le vide");
                        }
                    }
                }
                }
                    

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            jTextField7.setEditable(false);
            jLabel28.setText("Seulement les chiffres");
            jLabel29.setIcon(new ImageIcon("src\\Icons\\error.png"));
        } else {
            jTextField7.setEditable(true);
            jLabel28.setText("");
            jLabel29.setIcon(new ImageIcon(""));
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JComboBox<String> jComboBox1;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPasswordField jPasswordField1;
    public javax.swing.JPasswordField jPasswordField2;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
